spring:
  application:
    name: inventory-service
server:
  port: 8087
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8687/eureka/
      initialInstanceInfoReplicationIntervalSeconds: 5
      registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
logging:
  level:
    project:
      user:
        UserClient: DEBUG